### ISSUE TITLE
Error when building with ExtendedEditor.dll in Unity?

### ISSUE THREAD

**Issue by rotolonico** [LukaszKr/UnityPlugins#2]
I am using the PowerConsole library in Unity. It works fine in the editor but whenever I try to build the project I get this error: 

ArgumentException: The Assembly UnityEditor is referenced by ExtendedEditor ('Assets/Plugins/ProceduralLevel/ExtendedEditor/ExtendedEditor.dll'). But the dll is not allowed to be included or could not be found.

Any help would be greatly appreciated, thanks!

**Comment by LukaszKr** [comment]
Hello,

Can you please check in Editor if the ExtendedEditor.dll lib is correctly marked as editor only under „Select platforms for plugin”?
This dll is dependent on UnityEditor code which is not allowed into builds. If you are using it somewhere in your non-editor code, you might want to at least wrap it with #if UNITY_EDITOR

Od: Domenico Rotolo<mailto:notifications@github.com>
Wysłano: piątek, 6 grudnia 2019 19:14
Do: LukaszKr/UnityPlugins<mailto:UnityPlugins@noreply.github.com>
DW: Subscribed<mailto:subscribed@noreply.github.com>
Temat: [LukaszKr/UnityPlugins] Error when building with ExtendedEditor.dll in Unity? (#2)


I am using the PowerConsole library in Unity. It works fine in the editor but whenever I try to build the project I get this error:

ArgumentException: The Assembly UnityEditor is referenced by ExtendedEditor ('Assets/Plugins/ProceduralLevel/ExtendedEditor/ExtendedEditor.dll'). But the dll is not allowed to be included or could not be found.

Any help would be greatly appreciated, thanks!

**Comment by LukaszKr** [comment]
Can you please check in Editor if the ExtendedEditor.dll lib is correctly marked as editor only under „Select platforms for plugin”?
This dll is dependent on UnityEditor code which is not allowed into builds. If you are using it somewhere in your non-editor code, you might want to at least wrap it with #if UNITY_EDITOR

**Comment by LukaszKr** [comment]
I've pushed a commit to PowerConsole git that will fix import settings for this .dll.
If you want to fix it manually:
Go to ExtendedEditor -> in include Platforms deselect everything that is not Editor. This should help with the issue.

**Comment by rotolonico** [comment]
Thank you for the very quick reply!
My plan was to use the PowerConsole also in a standalone build, not only in the Editor. Is that possible even after building with the dll disabled?

**Comment by rotolonico** [comment]
> Thank you for the very quick reply!
> My plan was to use the PowerConsole also in a standalone build, not only in the Editor. Is that possible even after building with the dll disabled?

I am not sure if the issue I am getting is related or not, but basically, whenever I build the project and try to type a command in the PowerConsole, I don't get any new commands I had set from my code. (but I do see them when running in the Editor).
My question is: is that supposed to happen, meaning that PowerConsole is only supposed to be used in the Unity Editor and not in a Standalone Build or am I doing something wrong?

**Comment by LukaszKr** [comment]
Yes with this change it should properly build and work outside of editor without any issue.

**Comment by LukaszKr** [comment]
If you made a change and your code is building properly make sure console commands are not in the some #if block that would exclude them from builds.

**Comment by rotolonico** [comment]
I have replicated the ConsoleSetup.cs class from the example. [This](https://gist.github.com/rotolonico/c489ef4a5ff5a704b11b17d7ad95e101) is the script I use for adding the commands. It is attached to a Gameobject that loads as soon as the first scene loads.

**Comment by rotolonico** [comment]
> If you made a change and your code is building properly make sure console commands are not in the some #if block that would exclude them from builds.

I lucked out and figured out the problem:
I was using an obfuscator to properly secure my code and it seems as this interfered with the PowerConsole, not making it recognize the classes properly. Since this is just a testing tool, I have no problem disabling the obfuscator for now; just an heads up though!

Thank you for the active support, I'll close this now.

**Comment by LukaszKr** [comment]
That makes sense as method invocation is done with reflection and it just looks for "Command" by default.
You could fix that by overriding GetCommandName with something like this:

```
	public Message Command(int param1)
	{
		return new Message(EMessageType.Success, "Test Message");
	}

	public override MethodInfo GetCommandMethod()
	{
		return ((Func<int, Message>)Command).Method;
	}
```

This way it would not be affected by code obsfucator.

**Comment by rotolonico** [comment]
Oh, I didn't realize that, will do!
